---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc02
  labels:
    type: executor
spec:
  storageClassName: "standard"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
  labels:
    type: fetcher
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels:
    type: executor
spec:
  storageClassName: "standard"
  claimRef:
    name: pvc02
  capacity:
    storage: 500G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: sx4-agent
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    type: fetcher
spec:
  storageClassName: "standard"
  claimRef:
    name: pvc01
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: sx4-agent
    fsType: ext4