# Copyright 2019 Streamsets Inc.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels:
    type: executor
spec:
  claimRef:
    namespace: default
    name: pvc02
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    type: fetcher
spec:
  claimRef:
    namespace: default
    name: pvc01
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc02
  labels:
    type: executor
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
  labels:
    type: fetcher
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---          