# Copyright 2019 Streamsets Inc.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dirmount
  labels:
    type: dirmount
spec:
  claimRef:
    name: dirmount
    namespace: SEDTARGET1
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  hostPath:
    path: PATH_MOUNT
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dirmount
  labels:
    type: dirmount
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
